apiVersion: v1
kind: Service
metadata:
  name: myapp-loadbalancer-service
  labels:
    env: production
    app: myapp-project-1
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    env: production
    name: frontend-pod
    app: myapp-project-1
