apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    env: production
    name: frontend-pod
    app: myapp-project-1
spec:
  containers:
    - name: frontend
      image: alexgolubyatnikov/node-application-1 
