apiVersion: v1
kind: Service
metadata:
  name: service-nodejs
  labels:
    env: production
    name: service-nodejs
    app: demo-node-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    env: production
    name: nodejs-pod
    app: demo-node-app   
  
