apiVersion: v1
kind: Service
metadata:
  name: service-nodejs-loadbalancer
  labels:
    env: production
    name: service-nodejs-loadbalancer
    app: demo-node-app
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
  selector:
    env: production
    name: nodejs-pod
    app: demo-node-app   
  
