apiVersion: v1
kind: Service
metadata:
  name: service-node-pod
  labels:
    env: production
    name: service-node
    app: demo-node-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
  selector:
    env: production
    name: nginx-pod
    app: demo-node-app   
  