apiVersion: v1
kind: Service
metadata:
  name: service-redis-pod
  labels:
    env: production
    name: service-redis
    app: demo-node-app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    env: production
    name: redis-pod
    app: demo-node-app
