apiVersion: v1
kind: Service
metadata:
  name: hello-world
  labels:
    env: production
    name: service-hello-world
    app: demo-nodejs-hello-world-app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30002
      protocol: TCP
  selector:
    env: production
    name: nodejs-hello-world-pod
    app: demo-nodejs-hello-world-app    