apiVersion: v1
kind: Service
metadata:
  name: service-pod
  labels:
    env: production
    name: service-pod
    app: demo-node-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    env: production
    name: nginx-pod
    app: demo-node-app   
  