apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    env: production
    name: frontend-pod
    app: demo-node-app
spec:
  containers:
    - name: frontend
      image: brendanburns/journal-server:latest
