apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    env: production
    name: nodejs-hello-world-pod
    app: demo-nodejs-hello-world-app
spec:
  containers:
    - name:  helloworld-nodejs
      image: helloworld-nodejs-image
