apiVersion: v1
kind: Pod
metadata:
  name: nodejs-pod
  labels:
    env: production
    name: nodejs-pod
    app: demo-node-app
spec:
  containers:
    - name:  myapp-nodejs
      image: myapp-node-image
