apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: production
    name: nginx-pod
    app: demo-node-app
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80