apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    env: production
    name: redis-pod
    app: demo-node-app
spec:
  containers:
    - name: redis
      image: redis
      command:
        - "redis-server --requirepass 1Qaz2Wsx"
      ports:
        - containerPort: 6379   
